from __future__ import annotations

from python_agent.resolvers.app_catalog_service import AppRecord


STANDARD_DEFAULT_APP_IDS = {
    "access",
    "database_compare",
    "excel",
    "office",
    "onenote",
    "outlook",
    "powerpoint",
    "project",
    "spreadsheet_compare",
    "visio",
    "word",
    "acrobat_reader",
    "adobe_xd",
    "after_effects",
    "animate",
    "audition",
    "bridge",
    "illustrator",
    "indesign",
    "lightroom",
    "media_encoder",
    "photoshop",
    "premiere_pro",
    "substance_painter",
    "calculator",
    "camera",
    "character_map",
    "cmd",
    "computer_management",
    "control_panel",
    "device_manager",
    "disk_cleanup",
    "disk_management",
    "edge",
    "event_viewer",
    "explorer",
    "game_bar",
    "magnify",
    "microsoft_store",
    "narrator",
    "notepad",
    "on_screen_keyboard",
    "paint",
    "performance_monitor",
    "photos",
    "powershell",
    "print_management",
    "regedit",
    "remote_desktop_connection",
    "resource_monitor",
    "run",
    "services",
    "settings",
    "snipping_tool",
    "steps_recorder",
    "system_configuration",
    "system_information",
    "task_manager",
    "task_scheduler",
    "terminal",
    "voice_recorder",
    "windows_defender_firewall_with_advanced_security",
    "windows_media_player_legacy",
    "wmplayer",
}


def is_user_visible_app(record: AppRecord) -> bool:
    return record.source == "user" or record.app_id in STANDARD_DEFAULT_APP_IDS
